PAPER_API_KEY = "PKV6NDV7I00QIO7HS3DA"
PAPER_SECRET_KEY = "MecMHyyeghQ59N/k007diLf5F87PmwmVvf2AsNSc"
PAPER_BASE_URL = "https://paper-api.alpaca.markets"

LIVE_API_KEY = "AKBZZC10R4S5E20GCTYJ"
LIVE_SECRET_KEY = "fqExBFUBJYPFAaNcJkxNrbakIWlNcPt/x5DoFNMk"
LIVE_BASE_URL = "https://api.alpaca.markets"
